Revert "Merge master from AdmitHub/meteor-buildpack-horse.git"
This reverts commit 5c9df43ef8964800a03dc58679f3afd887934142, reversing
changes made to 156d7554148ab900b42661b8c007e91780195f57.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 #
 # Heroku buildpack for Meteor
@@ -38,8 +38,8 @@ BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
 APP_CHECKOUT_DIR=$1
 CACHE_DIR=$2
 if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
-  echo "-----> Clearing cache dir."
-  rm -rf "$CACHE_DIR/*"
+  echo "----> Clearing cache dir."
+  rm -rf "$CACHE_DIR"
 fi
 
 #
@@ -64,8 +64,10 @@ if [ ! -d "$APP_SOURCE_DIR/.meteor" ]; then
   exit 1
 fi
 
+APP_RELEASE=`cat "$APP_SOURCE_DIR/.meteor/release" | sed -e 's/METEOR@//'`
+
 # Where we will install meteor. Has to be outside the APP_CHECKOUT_DIR.
-METEOR_DIR="$CACHE_DIR/meteor"
+METEOR_DIR="$CACHE_DIR/$APP_RELEASE"
 # Where we'll put things we compile.
 COMPILE_DIR_SUFFIX=".meteor/heroku_build"
 COMPILE_DIR="$APP_CHECKOUT_DIR"/"$COMPILE_DIR_SUFFIX"
@@ -95,63 +97,48 @@ fi
 # Install meteor
 #
 
-# Install the latest meteor, and rely on meteor to upgrade/downgrade itself to
-# the .meteor/release target.
-if [ -e "$METEOR_DIR/.meteor/meteor" ]; then
-  echo "-----> Existing meteor installation found, using it."
-else
+if [ ! -e "$METEOR_DIR/.meteor/meteor" ]; then
   echo "-----> Installing meteor"
-  curl -sS "https://install.meteor.com/" | HOME="$METEOR_DIR" /bin/sh
+  curl -sS "https://install.meteor.com/?release=$APP_RELEASE" | HOME="$METEOR_DIR" /bin/sh
 fi
-# Function to execute meteor with proper HOME.
-function METEOR {
-  ARGS=$@
-  HOME="$METEOR_DIR" "$METEOR_DIR/.meteor/meteor" $ARGS
-}
+METEOR="$METEOR_DIR/.meteor/meteor" # The meteor binary.
+
+echo "-----> Meteor version: `HOME=$METEOR_DIR $METEOR --version`"
 
 #
 # Build the meteor app!
 #
-
-# Change into the project directory. Once we're there, 'meteor' commands will
-# run with the context of the target release (project .meteor/release) rather
-# than the "latest" that is installed by install.meteor.com.
 cd "$APP_SOURCE_DIR"
 
-echo "-----> Target Meteor version: `METEOR --version`"
-
-# Deal with non-server build targets.  Determine if we have --server-only flag
-# capability (Meteor 1.3 and up).
+# Determine if we have --server-only flag capability. Allow non-zero return from grep.
 echo "-----> Checking if this meteor version supports --server-only"
-# Allow non-zero return from grep.
 set +e
-HAS_SERVER_ONLY=`METEOR help build | grep -e '--server-only'`
+HAS_SERVER_ONLY=`HOME=$METEOR_DIR $METEOR help build | grep -e '--server-only'`
 set -e
 if [ -n "$HAS_SERVER_ONLY" ] ; then
   SERVER_ONLY_FLAG='--server-only'
 else
   SERVER_ONLY_FLAG=""
 fi
-# Remove the Android platform if we don't support the --server-only flag
-# (Meteor 1.2 and below).  iOS platform gets ignored properly.
+# Remove the Android platform if we don't support the --server-only flag.  iOS
+# platform gets ignored properly.
 if [ -z "$SERVER_ONLY_FLAG" ]; then
   echo "-----> Attempting to remove android platform."
-  METEOR remove-platform android || true
+  HOME=$METEOR_DIR $METEOR remove-platform android || true
   echo "-----> Moving on."
 fi
 
-# Identify the npm/node to use. We need to copy the node binary out to get the
-# correct version in the built slug (e.g. 0.10.x for Meteor<1.4, 4.x for
-# Meteor>=1.4).  We can't copy the whole meteor world because that's too large
-# (Issue #125).
+# Identify the npm/node to use. While we could use `meteor node` and `meteor
+# npm` to execute these directly, to use them in prod, we'd need to copy the
+# meteor world into the built slug, and that's too large (Issue #125).
+# Instead, search for the binaries within meteor, and copy them into our built
+# slug.
 
-# Query node for its own path. As long as the Meteor version we got from
-# install.meteor.com is >=1.3, "meteor node" is available, even if the target
-# release predates that feature.
-METEOR_NODE=`METEOR node -e "process.stdout.write(process.execPath)"`
-# Assume npm is in the same dir as node.
-METEOR_NPM="`dirname "$METEOR_NODE"`/npm"
-
+METEOR_NPM=`find $METEOR_DIR -wholename "*/dev_bundle/bin/npm"`
+METEOR_NODE=`find $METEOR_DIR -wholename "*/dev_bundle/bin/node"`
+# Trim whitespace
+METEOR_NPM=`echo "$METEOR_NPM" | sed -e 's/[[:space:]]*$//'`
+METEOR_NODE=`echo "$METEOR_NODE" | sed -e 's/[[:space:]]*$//'`
 if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
   echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
   exit 1
@@ -174,7 +161,7 @@ if [ -e "$APP_SOURCE_DIR"/package.json ]; then
   $METEOR_NPM install
 fi
 
-# Related to https://github.com/meteor/meteor/issues/2796 and
+# Related to https://github.com/meteor/meteor/issues/2796 and 
 # https://github.com/meteor/meteor/issues/2606.  Some packages only build their
 # assets at runtime, and thus they are not available for bundling unless meteor
 # has been launched.  To opt-in to this, set BUILDPACK_PRELAUNCH_METEOR=1.
@@ -182,8 +169,8 @@ if [ -n "${BUILDPACK_PRELAUNCH_METEOR+1}" ]; then
   echo "-----> BUILDPACK_PRELAUNCH_METEOR: Pre-launching meteor to build packages assets"
   # Remove the Android platform because it fails due to the Android tools not
   # being installed, but leave the iOS platform because it's ignored.
-  METEOR remove-platform android || true
-  HOME=$METEOR_DIR timeout -s9 180 $METEOR_DIR/.meteor/meteor --settings settings.json || true
+  HOME=$METEOR_DIR $METEOR remove-platform android || true
+  HOME=$METEOR_DIR timeout -s9 180 $METEOR --settings settings.json || true
 fi
 
 # Now on to bundling. Don't put the bundle in $APP_CHECKOUT_DIR during
@@ -193,13 +180,13 @@ echo "-----> Building Meteor app with ROOT_URL: $ROOT_URL"
 BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
 
 # The actual invocation of `meteor build`!
-METEOR build $BUILD_OPTIONS --server $ROOT_URL $SERVER_ONLY_FLAG --directory $BUNDLE_DEST
+HOME=$METEOR_DIR $METEOR build $BUILD_OPTIONS --server $ROOT_URL $SERVER_ONLY_FLAG --directory $BUNDLE_DEST
 
 echo "-----> Moving built slug to $COMPILE_DIR/app"
 mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
 rmdir $BUNDLE_DEST
 
-# Run npm install on the built slug; only for '--production' dependencies.
+# Run npm install on the built slug; only for `--production` dependencies.
 echo "-----> Installing npm production dependencies on built slug"
 if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
   cd "$COMPILE_DIR"/app/programs/server
@@ -229,11 +216,3 @@ echo "-----> Running extras"
 for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
   . "$BUILDPACK_DIR"/extra/$file
 done
-
-#
-# Clear cache after build is done
-#
-if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
-  echo "-----> Clearing cache dir."
-  rm -rf $METEOR_DIR
-fi
